descriptor-schema-version: "2.4"

info:
  name: iox-aarch64-secure-storage-demo
  description: "Small Linux with CURL to test IOx Secure Storage"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  type: docker
  cpuarch: aarch64
  resources:
    profile: custom
    cpu: 100
    memory: 32
    disk: 10

    network:
      -
        interface-name: eth0
  # Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: "/iox-ss-stress-test.sh"
    